fqbn: 
  - arduino:avr:uno
  - arduino:avr:nano
  - arduino:avr:mega
  - arduino:renesas_uno:minima
  - arduino:renesas_uno:unor4wifi
  - arduino:samd:mkrzero
  - Infineon:xmc:XMC1100_XMC2GO
  - Infineon:xmc:XMC1300_Boot_Kit
  - Infineon:xmc:XMC1400_XMC2GO
  - Infineon:xmc:XMC1400_Arduino_Kit
  - Infineon:xmc:XMC4700_Relax_Kit
  - Infineon:xmc:XMC1100_Boot_Kit
  - infineon:psoc6:cy8ckit_062s2_ai

additional_urls:
  - core: Infineon:xmc
    url:  https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json
  - core: infineon:psoc6
    url:  https://github.com/Infineon/arduino-core-psoc6/releases/latest/download/package_psoc6_index.json