name: Compile examples

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      core-setup-script:
        required: false
        type: string
        default: null
        description: 'Any setup script to run before building the Arduino package'
      ci-setup-script:
        required: false
        type: string
        default: null
        description: 'Any setup script to run before compiling the examples'
      os-list:
        required: false
        type: string
        default: 'ubuntu-latest, windows-latest, macos-latest'
        description: 'The list of operating systems to run the job on. The list should be a comma-separated string, e.g. "ubuntu-latest,windows-latest,macos-latest"'

jobs:
  package-core: 
    uses: Infineon/arduino-devops/.github/workflows/package-core.yml@latest
    with:
      setup-script: ${{ inputs.core-setup-script }}
      release: false

  ci-setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Checkout arduino-devops 
        uses: actions/checkout@v4
        with:
          repository: Infineon/arduino-devops
          ref: latest
          path: arduino-devops

      - name: Set build matrix
        id: set-matrix
        run: |
          matrix_ci=$(python ./arduino-devops/arduino-ci.py config --list fqbn)
          echo $matrix_ci
          echo "matrix="$matrix_ci"" >> $GITHUB_OUTPUT

  compile-examples-ubuntu:
    name: ubuntu
    if: contains(inputs.os-list, 'ubuntu')
    needs: 
      - ci-setup
      - package-core
    uses : Infineon/arduino-devops/.github/workflows/compile-examples-os.yml@latest
    with:
      ci-matrix-json: ${{ needs.ci-setup.outputs.matrix }}
      setup-script: ${{ inputs.ci-setup-script }}
      os: ubuntu-latest

  compile-examples-windows:
    name: windows
    if: contains(inputs.os-list, 'windows')
    needs: 
      - ci-setup
      - package-core
    uses : Infineon/arduino-devops/.github/workflows/compile-examples-os.yml@latest
    with:
      ci-matrix-json: ${{ needs.ci-setup.outputs.matrix }}
      setup-script: ${{ inputs.ci-setup-script }}
      os: windows-latest

  compile-examples-macos:
    name: macos
    if: contains(inputs.os-list, 'macos')
    needs: 
      - ci-setup
      - package-core
    uses : Infineon/arduino-devops/.github/workflows/compile-examples-os.yml@latest
    with:
      ci-matrix-json: ${{ needs.ci-setup.outputs.matrix }}
      setup-script: ${{ inputs.ci-setup-script }}
      os: macos-latest
