name: Compile examples

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      setup-script:
        required: false
        type: string
        default: null
        description: 'Any setup script to run before building the Arduino package and compiling the examples'
      ci-matrix-file-json:
        required: true
        type: string
        description: 'The file containing the build matrix in JSON format'

jobs:

  set-ci-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set build matrix
        id: set-matrix
        run: |
          matrix_ci=$(cat ${{ inputs.ci-matrix-file-json }})
          echo $matrix_ci
          echo "matrix="$matrix_ci"" >> $GITHUB_OUTPUT

  compile-examples:
    needs: set-ci-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix: ${{fromJson(needs.set-ci-matrix.outputs.matrix)}}

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout arduino-devops
        uses: actions/checkout@v4
        with:
          repository: Infineon/arduino-devops
          ref: latest
          path: arduino-devops

      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r arduino-devops/requirements.txt
        
      - name: Install arduino-cli Linux
        if: runner.os == 'Linux'
        run: |
          ./arduino-devops/arduino-cli-install.sh 1.1.0

      - name: Install arduino-cli Windows
        if: runner.os == 'Windows'
        run: |
          .\arduino-devops\arduino-cli-install.ps1 1.1.0 

      - name: Core setup
        if : ${{ inputs.setup-script }} != null
        run: |
          ${{ inputs.setup-script }}

      - name: Pack Arduino core
        run: |
          python ./arduino-devops/arduino-packager.py --no-version-check --no-previous-releases
  
      - name: Install Arduino core
        run: |
          python ./arduino-devops/pckg-install-local.py --pckg-dir build

      - name: Compile Sketch
        run: |
          arduino-cli compile --clean --verbose --fqbn ${{ matrix.fqbn }} ${{ matrix.example }}