name: Compile examples for OS

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      ci-matrix-json:
        required: true
        type: string
        description: 'The ci compile matrix in JSON format'
      setup-script:
        required: false
        type: string
        default: null
        description: 'Any setup script to run before compiling the examples'
      os:
        required: true
        type: string
        description: 'The operating system to run the job on'

jobs:  
  compile-examples:
    name: ${{ inputs.os }} - ${{ matrix.fqbn }}
    runs-on: ${{ inputs.os }}

    strategy:
      matrix: ${{fromJson(inputs.ci-matrix-json)}}

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Checkout arduino-devops
        uses: actions/checkout@v4
        with:
          repository: Infineon/arduino-devops
          ref: latest
          path: arduino-devops
          
      - name: Install python dependencies
        if: contains(inputs.os, 'windows') || contains(inputs.os, 'macos')
        run: |
          python -m pip install --upgrade pip
          pip install -r arduino-devops/requirements.txt

      - name: Compile setup
        if : ${{ inputs.setup-script }} != null
        run: |
          ${{ inputs.setup-script }}

      - name: Install arduino-cli
        run: |
          python ./arduino-devops/arduino-cli-install.py 1.2.0

      - name: Retrieve core package
        uses: actions/download-artifact@v4
  
      - name: Install arduino core
        run: |
          # The package is downloaded in the directory arduino-core-package
          python ./arduino-devops/pckg-install-local.py --pckg-dir arduino-core-package

      - name: Compile sketches
        run: |
          python ./arduino-devops/arduino-ci.py compile --fqbn ${{ matrix.fqbn }}