name: Release

on:
  release:
    types: published
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+**'
  workflow_call:
    inputs:
      release-title:
        required: true
        type: string
        description: 'The title of the release'
      setup-script:
        required: false
        type: string
        default: null
        description: 'Any setup script to run before building the release assets'

jobs:

  core-package:
    if: startsWith(github.ref, 'refs/tags/')
    uses: Infineon/arduino-devops/.github/workflows/package-core.yml@latest
    with:
      setup-script: ${{ inputs.setup-script }}
      release: true
    secrets: inherit

  release:
    needs: core-package
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Retrieve core package
      uses: actions/download-artifact@v4

    - name: Build release changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ inputs.release-title }} ${{  github.ref_name  }}
        files: |
          arduino-core-package/*.zip
          arduino-core-package/*.json
        body: ${{steps.build_changelog.outputs.changelog}}